apiVersion: v1
kind: Secret

metadata:
  name: backend-secret

type: Opaque

stringData:
  DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
  JWT_REFRESH_SECRET: {{ .Values.secret.jwtRefreshSecret | quote }}
  SMTP_PASSWORD: {{ .Values.secret.smtpPassword | quote }}
  CLOUDINARY_API_SECRET: {{ .Values.secret.cloudinaryApiSecret | quote }}
